// Generated by CoffeeScript 1.7.1
(function() {
  var Client, request;

  request = require('request');

  Client = (function() {
    function Client(token) {
      this.token = token;
      this.host = 'api.tinysou.com';
      this.version = 'v1';
      this.userAgent = "Tinysou-Node/" + (require('../package.json').version);
      this.baseUrl = "http://" + this.host + "/" + this.version;
      this.headers = {
        'User-Agent': this.userAgent,
        'Authorization': "token " + this.token
      };
    }

    Client.prototype._buildUrl = function(path) {
      return this.baseUrl + path;
    };

    Client.prototype.request = function(method, path, params, body, callback) {
      return request({
        method: method,
        qs: params,
        url: this._buildUrl(path),
        body: body,
        json: true,
        headers: this.headers
      }, function(err, res, body) {
        if (err) {
          return callback(err);
        } else if (res.statusCode >= 400) {
          return callback(body);
        } else if (res.statusCode === 204) {
          return callback(null, true);
        } else {
          return callback(null, body);
        }
      });
    };

    Client.prototype.get = function(path, params, callback) {
      return this.request('GET', path, params, null, callback);
    };

    Client.prototype.post = function(path, body, callback) {
      return this.request('POST', path, null, body, callback);
    };

    Client.prototype.put = function(path, body, callback) {
      return this.request('PUT', path, null, body, callback);
    };

    Client.prototype["delete"] = function(path, params, callback) {
      return this.request('DELETE', path, params, null, callback);
    };

    return Client;

  })();

  module.exports = Client;

}).call(this);
