// Generated by CoffeeScript 1.7.1
(function() {
  var Client, request;

  request = require('request');

  Client = (function() {
    function Client(token) {
      this.token = token;
      this.host = 'api.tinysou.com';
      this.version = 'v1';
      this.userAgent = "Tinysou-Node/" + (require('../package.json').version);
      this.baseUrl = "http://" + this.host + "/" + this.version;
      this.headers = {
        'User-Agent': this.userAgent,
        'Authorization': "token " + this.token
      };
    }

    Client.prototype._buildUrl = function(path) {
      return this.baseUrl + path;
    };

    Client.prototype.get = function(path, params, callback) {
      return request({
        method: 'GET',
        qs: params,
        url: this._buildUrl(path),
        json: true,
        headers: this.headers
      }, function(err, res, body) {
        if (err) {
          return callback(err);
        } else {
          return callback(null, body);
        }
      });
    };

    Client.prototype.post = function(path, payload, callback) {
      return request({
        method: 'POST',
        body: payload,
        url: this._buildUrl(path),
        json: true,
        headers: this.headers
      }, function(err, res, body) {
        if (err) {
          return callback(err);
        } else {
          return callback(null, body);
        }
      });
    };

    Client.prototype.put = function(path, payload, callback) {
      return request({
        method: 'PUT',
        body: payload,
        url: this._buildUrl(path),
        json: true,
        headers: this.headers
      }, function(err, res, body) {
        if (err) {
          return callback(err);
        } else {
          return callback(null, body);
        }
      });
    };

    Client.prototype["delete"] = function(path, params, callback) {
      return request({
        method: 'DELETE',
        qs: params,
        url: this._buildUrl(path),
        json: true,
        headers: this.headers
      }, function(err, res, body) {
        if (err) {
          return callback(err);
        } else {
          return callback(null, true);
        }
      });
    };

    return Client;

  })();

  module.exports = Client;

}).call(this);
