// Generated by CoffeeScript 1.7.1
(function() {
  var Collection;

  Collection = (function() {
    function Collection(client) {
      this.client = client;
    }

    Collection.prototype.list = function(engineName, callback) {
      return this.client.get("/engines/" + engineName + "/collections", {}, callback);
    };

    Collection.prototype.create = function(engineName, collection, callback) {
      return this.client.post("/engines/" + engineName + "/collections", collection, callback);
    };

    Collection.prototype.get = function(engineName, collectionName, callback) {
      return this.client.get("/engines/" + engineName + "/collections/" + collectionName, {}, callback);
    };

    Collection.prototype["delete"] = function(engineName, collectionName, callback) {
      return this.client["delete"]("/engines/" + engineName + "/collections/" + collectionName, {}, callback);
    };

    return Collection;

  })();

  module.exports = Collection;

}).call(this);
