// Generated by CoffeeScript 1.7.1
(function() {
  var Document;

  Document = (function() {
    function Document(client) {
      this.client = client;
    }

    Document.prototype.list = function(engineName, collectionName, callback) {
      return this.client.get("/engines/" + engineName + "/collections/" + collectionName + "/documents", {}, callback);
    };

    Document.prototype.create = function(engineName, collectionName, document, callback) {
      return this.client.post("/engines/" + engineName + "/collections/" + collectionName + "/documents", document, callback);
    };

    Document.prototype.get = function(engineName, collectionName, documentId, callback) {
      return this.client.get("/engines/" + engineName + "/collections/" + collectionName + "/documents/" + documentId, {}, callback);
    };

    Document.prototype.update = function(engineName, collectionName, documentId, document, callback) {
      return this.client.put("/engines/" + engineName + "/collections/" + collectionName + "/documents/" + documentId, document, callback);
    };

    Document.prototype["delete"] = function(engineName, collectionName, documentId, callback) {
      return this.client["delete"]("/engines/" + engineName + "/collections/" + collectionName + "/documents/" + documentId, {}, callback);
    };

    return Document;

  })();

  module.exports = Document;

}).call(this);
