// Generated by CoffeeScript 1.7.1
(function() {
  var Search;

  Search = (function() {
    function Search(client) {
      this.client = client;
    }

    Search.prototype.single = function(engineName, collectionName, searchInfo, callback) {
      return this.client.post("/engines/" + engineName + "/collections/" + collectionName + "/search", searchInfo, callback);
    };

    Search.prototype.many = function(engineName, searchInfo, callback) {
      return this.client.post("/engines/" + engineName + "/search", searchInfo, callback);
    };

    return Search;

  })();

  module.exports = Search;

}).call(this);
